version: '3'
services:
  db:
    image: postgres:13
    container_name: 'broker-report-api-database'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - DB_USERNAME=postgres
    networks:
      - broker-project
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
    - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    networks:
      - broker-project
      - default
  redis:
    image: redis:alpine
    env_file:
    - .env
    command: redis-server
    ports:
      - "6380:6380"
    expose:
      - "6380"
    networks:
      - default
  sneakers:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rake sneakers:run
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - web
    networks:
      - broker-project
      - default

volumes:
  database:

networks:
  broker-project:
    external: true