version: '3'
services:
  db:
    image: postgres:13
    container_name: 'broker-report-api-database'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - DB_USERNAME=postgres
    networks:
      - broker_report
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
    - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - broker_report
      - default

volumes:
  database:

networks:
  broker_report:
    external: true